# Possible values: "Legacy", "Start", "End", "Center", "SpaceAround", "SpaceBetween"
layout = "SpaceAround"

# Window width
# Possible values: "auto" or a positive integer
width = "auto"

esc_quit        = true
toggle_scanning = "s"

[adapter]
toggle_discovery = "d"
toggle_pairing   = "p"
toggle_power     = "o"

[paired_device]
rename          = "e"
toggle_favorite = "f"
toggle_trust    = "t"
unpair          = "u"
