# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = """ $shell$os$hostname$username$directory$git_branch$git_status$nodejs$package"""

# Drop ugly default prompt characters
[character]
success_symbol = ''
error_symbol = ''

# ------------------------------------

[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Windows = ' '
Arch = ' 󰣇'
Ubuntu = ' '
Macos = ' 󰀵'

# Shows the Username
[username]
show_always = true
style_root = "bold red"
style_user = "bold gray"
format = "[$user]($style) "
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold yellow)/'
disabled = false

# Shows current directory
[directory]
truncation_length = 1
# truncation_symbol = ' '
truncation_symbol = ' '
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
format = '[$symbol$branch]($style)'
symbol = " "
truncation_symbol = '…/'
style = 'bold red'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'
stashed = ' '
modified = ' '
staged = '[ ++\($count\)](green)'
renamed = ' 襁'
deleted = ' '
windows_starship = '/mnt/c/Users/gaura/.config/starship.exe'

# Shows current nodejs
[nodejs]
format = '[$symbol ($version )]($style)'
symbol = ""
not_capable_style = "bold red"

# Shows current shell
[shell]
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
bash_indicator = ''
zsh_indicator = ''
cmd_indicator = ''
style = 'bold'
disabled = false
