# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = """ $shell$os$username$hostname$kubernetes$directory$git_branch$git_status$nodejs$package"""

# Drop ugly default prompt characters
[character]
success_symbol = '[󰄴](bold green)'
error_symbol = '[] (bold red)'

# Shows the currently used shell
[shell]
powershell_indicator = '_'
unknown_indicator = ''
bash_indicator = ''
zsh_indicator = ''
cmd_indicator = ''
style = 'bold'
disabled = false

# Shows the os
[os]
format = '[$symbol](bold white) '
disabled = false

# os symbols
[os.symbols]
Windows = ' '
Arch = ' 󰣇'
Ubuntu = ' '
Macos = ' 󰀵'

# Shows the username
[username]
style_user = 'yellow bold'
style_root = 'black bold'
format = '[ ](white bold)[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)'
disabled = false

# Shows current directory
[directory]
truncation_length = 1
truncation_symbol = ' '
truncate_to_repo = true
home_symbol = '󰋜 ~'
read_only_style = ' 197'
read_only = ' '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
format = '[$symbol$branch]($style)'
symbol = " "
truncation_symbol = '…/'
style = 'bold red'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'
stashed = ' '
modified = ' '
staged = '[ ++\($count\)](green)'
renamed = ' 襁'
deleted = ' '
windows_starship = '/mnt/c/Users/gaura/.config/starship.exe'

# Shows current nodejs
[nodejs]
format = '[$symbol ($version )]($style)'
symbol = ""
not_capable_style = "bold red"

# Shows kubernetes context and namespace
[kubernetes]
format = '[󱃾 $context\($namespace\)](bold purple) '
disabled = false
